
#ifndef _COLUMN_CH
#define _COLUMN_CH

#define TBCT_TEXT               1
#define TBCT_BITMAP             2

#define TBCT_LEFT               0
#define TBCT_RIGHT             16
#define TBCT_CENTER            32

#define TBCT_TEXTLEFT          TBCT_TEXT + TBCT_LEFT
#define TBCT_TEXTRIGHT         TBCT_TEXT + TBCT_RIGHT
#define TBCT_TEXTCENTER        TBCT_TEXT + TBCT_CENTER

#define TBCT_TREE              64

#endif
