#IFDEF SPANISH
         #define STR0001  "bUscar    "
         #define STR0002  "Visualizar"
         #define STR0003  "Saldos por Sublote"
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Search   "
         #define STR0002  "View      "
         #define STR0003  "Balance per SubLot "
   #ELSE
         #define STR0001  "Pesquisar"
         #define STR0002  "Visualizar"
         #define STR0003  "Saldos por Sub-Lote"
   #ENDIF
#ENDIF
