#IFDEF SPANISH
         #define STR0001  "bUscar"
         #define STR0002  "Visualizar"
         #define STR0003  "Saldos por Localizaci¢n"
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Search  "
         #define STR0002  "View   "
         #define STR0003  "Balances per Location "
   #ELSE
         #define STR0001  "Pesquisar"
         #define STR0002  "Visualizar"
         #define STR0003  "Saldos por Localiza‡„o"
   #ENDIF
#ENDIF