#IFDEF SPANISH
	#define STR0001  "Al¡cuota"
   #define STR0002  "Valor Base"
   #define STR0003  "Vlr. Impuesto"
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Aliquota"
         #define STR0002  "Valor Base"
         #define STR0003  "Val. Imposto"
   #ELSE
         #define STR0001  "Aliquota"
         #define STR0002  "Valor Base"
         #define STR0003  "Val. Imposto"
   #ENDIF
#ENDIF