#IFDEF SPANISH
      #define STR0001  "®&QuÇ es esto?"
      #define STR0002  "Consulta Est†ndar"
      #define STR0003  "F3 Disponible..."
#ELSE
	#IFDEF ENGLISH
	   #define STR0001  "&O que Ç isto?"
	   #define STR0002  "Consulta Padr∆o"
      #define STR0003  "F3 Dispon°vel..."
	#ELSE
	   #define STR0001  "&O que Ç isto?"
	   #define STR0002  "Consulta Padr∆o"
      #define STR0003  "F3 Dispon°vel..."
	#ENDIF
#ENDIF
