#IFDEF SPANISH
   #define STR0001  "F3 Disponible..."
   #define STR0002  "®&QuÇ es esto?"
   #define STR0003  "Consulta Est†ndar"
#ELSE
	#IFDEF ENGLISH
	   #define STR0001  "F3 Dispon°vel..."
	   #define STR0002  "&O que Ç isto?"
	   #define STR0003  "Consulta Padr∆o"
	#ELSE
	   #define STR0001  "F3 Dispon°vel..."
	   #define STR0002  "&O que Ç isto?"
	   #define STR0003  "Consulta Padr∆o"
	#ENDIF
#ENDIF
