#IFDEF SPANISH
   #define STR0001  "Sin Nombre "
   #define STR0002  "¨Desea borrar este atajo? "
   #define STR0003  "Atenci¢n"
#ELSE
   #IFDEF ENGLISH
	   #define STR0001  "Sem Nome..."
	   #define STR0002  "Deseja excluir este atalho?"
	   #define STR0003  "Aten‡Æo"
   #ELSE
	   #define STR0001  "Sem Nome..."
	   #define STR0002  "Deseja excluir este atalho?"
	   #define STR0003  "Aten‡Æo"
	#ENDIF		
#ENDIF