#IFDEF SPANISH
         #define STR0001  "Öndices del ICPv"
         #define STR0002  "La Suma de los factores debe ser 1"
         #define STR0003  "Atenci¢n"
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Indices do IQF"
         #define STR0002  "A Soma dos fatores deve ser 1"
         #define STR0003  "Aten‡Æo"
   #ELSE
         #define STR0001  "Indices do IQF"
         #define STR0002  "A Soma dos fatores deve ser 1"
         #define STR0003  "Aten‡Æo"
   #ENDIF
#ENDIF