#IFDEF SPANISH
			#define STR0001  "Indexando Archivo..."
			#define STR0002  "Rec lculo t‚rminado com suceso"
#ELSE
	#IFDEF ENGLISH
                        #define STR0001  "Indexing File ......"
                        #define STR0002  "Recalcul.executed successfully "
	#ELSE
			#define STR0001  "Indexando Arquivo..."
			#define STR0002  "Rec lculo encerrado com sucesso"
	#ENDIF
#ENDIF
