#IFDEF SPANISH
         #define STR0001  "Treinamento"
         #define STR0002  "Matriz"
         #define STR0003  "T‚rmino Normal"
#ELSE
   #IFDEF ENGLISH
         #define STR0001  "Treinamento"
         #define STR0002  "Matriz"
         #define STR0003  "T‚rmino Normal"
   #ELSE
         #define STR0001  "Treinamento"
         #define STR0002  "Matriz"
         #define STR0003  "T‚rmino Normal"
   #ENDIF
#ENDIF