#IFDEF SPANISH
   #define STR0001  "Financiero"
   #define STR0002  "Financiero Siga Advanced "
   #define STR0003  "T‚rmino Normal"
#ELSE
   #IFDEF ENGLISH
      #define STR0001  "Financial "
      #define STR0002  "Siga Advanced Financial  "
      #define STR0003  "Normal End     "
   #ELSE
      #define STR0001  "Financeiro"
      #define STR0002  "Financeiro Siga Advanced "
      #define STR0003  "T‚rmino Normal"
   #ENDIF
#ENDIF