/*----------------------------------------------------------\
| TOTVS - HUB NORTE DE AMERICA LATINA						|
|-----------------------------------------------------------|
|    PROGRAMA: ARXLJFAT.PRW									|
|    OBJETIVO: Impresión de Factura en Control de Tiendas	|
| RESPONSABLE: Erick Christian Rosales Cruz					|
|       FECHA: Diciembre del 2012							|
\----------------------------------------------------------*/

